@startuml
actor "Korisnik" as User

rectangle "Mini alarmni sustav" {
  usecase "Unos PIN-a" as UC1
  usecase "Odabir PIR senzora" as UC2
  usecase "Odabir plinskog senzora" as UC3
  usecase "Resetiranje PIN-a" as UC4
  usecase "Promjena PPM granice" as UC5
  usecase "Gašenje alarma unosom PIN-a" as UC6
  usecase "Automatska detekcija plina i pokreta" as UC7
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC6
UC2 --> UC7
UC3 --> UC7

@enduml
