@startuml
actor Sustav

rectangle "Mini Alarmni Sustav - poslovni procesi" {
  usecase "Sleep mode"
  usecase "Automatska detekcija pokreta (PIR)"
  usecase "Automatska detekcija plina"
  usecase "Aktivacija alarma"
  usecase "Reakcija na ispravan PIN"
  usecase "Praćenje i prikaz statusa"
}

Sustav --> "Sleep mode"
"Sleep mode" --> "Automatska detekcija pokreta (PIR)"
"Sleep mode" --> "Automatska detekcija plina"
Sustav --> "Aktivacija alarma"
Sustav --> "Reakcija na ispravan PIN"
Sustav --> "Praćenje i prikaz statusa"
@enduml