name: Generate UML Diagrams with PlantUML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Generate diagrams
        run: |
          mkdir -p output
          plantuml -tpng -o output *.puml

      - name: Upload diagrams as artifact
        uses: ./github/actions/upload-artifact
        with:
          name: uml-diagrams
          path: output
