name: Generate UML Diagrams with PlantUML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-diagrams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PlantUML
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml

      - name: Generate UML diagrams
        run: |
          mkdir -p output
          plantuml -tpng -o output *.puml

      - name: Upload UML diagrams
        uses: actions/upload-artifact@v2
        with:
          name: uml-diagrams
          path: output
